# Generated by Django 5.0.6 on 2026-08-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_salarypayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="team_login_limit",
        ),
    ]
