# Generated by Django 5.0.6 on 2026-08-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_shop_plan_remove_shop_team_login_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="garmentitem",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="shop",
            name="currency_symbol",
            field=models.CharField(default="₹", max_length=8),
        ),
        migrations.AddField(
            model_name="shop",
            name="default_daily_wage",
            field=models.FloatField(default=600.0),
        ),
        migrations.AddField(
            model_name="shop",
            name="default_staff_role",
            field=models.CharField(default="Washer", max_length=100),
        ),
        migrations.AddField(
            model_name="shop",
            name="express_multiplier",
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name="shop",
            name="locale",
            field=models.CharField(default="en_IN", max_length=16),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Supplies", "Supplies"),
                    ("Rent", "Rent"),
                    ("Utilities", "Utilities"),
                    ("Maintenance", "Maintenance"),
                    ("Salary", "Salary"),
                    ("Transport", "Transport"),
                    ("Other", "Other"),
                ],
                default="Supplies",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("UPI", "UPI"),
                    ("CARD", "Card"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                ],
                default="CASH",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("UPI", "UPI"),
                    ("CARD", "Card"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                ],
                default="CASH",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="salarypayment",
            name="method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("UPI", "UPI"),
                    ("CARD", "Card"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                ],
                default="CASH",
                max_length=50,
            ),
        ),
    ]
