# Generated by Django 5.0.6 on 2026-08-20 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_garmentcategory_turnaround_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLACED", "Placed"),
                            ("PROCESSING", "Processing"),
                            ("IRONING", "Ironing"),
                            ("READY", "Ready"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_log",
                        to="api.order",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
