# Generated by Django 5.2.17 on 2026-09-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_shop_default_daily_wage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
