# Generated by Django 5.0.6 on 2026-09-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_attendance_check_in_time_attendance_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
