# Generated by Django 5.0.6 on 2026-07-30 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("area", models.CharField(blank=True, default="", max_length=120)),
                ("total_orders", models.IntegerField(default=0)),
                ("total_spent", models.FloatField(default=0.0)),
                ("due_amount", models.FloatField(default=0.0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(default="Supplies", max_length=100)),
                ("amount", models.FloatField()),
                ("payment_method", models.CharField(default="CASH", max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GarmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(default="Shirt", max_length=50)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Garment categories",
            },
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("pin_code", models.CharField(blank=True, default="", max_length=12)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="LaundryBill Express", max_length=255),
                ),
                (
                    "owner_name",
                    models.CharField(default="Aditya Sharma", max_length=255),
                ),
                ("phone", models.CharField(default="+91 98765 43210", max_length=50)),
                ("whatsapp", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "address",
                    models.TextField(default="123 MG Road, Connaught Place, New Delhi"),
                ),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("state", models.CharField(blank=True, default="", max_length=120)),
                ("pin_code", models.CharField(blank=True, default="", max_length=12)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("gstin", models.CharField(default="07AAAAA0000A1Z5", max_length=50)),
                ("pan", models.CharField(blank=True, default="", max_length=20)),
                ("tax_rate", models.FloatField(default=5.0)),
                (
                    "account_holder_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("ifsc_code", models.CharField(blank=True, default="", max_length=20)),
                ("bank_name", models.CharField(blank=True, default="", max_length=255)),
                ("upi_id", models.CharField(blank=True, default="", max_length=120)),
                (
                    "order_prefix",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("pickup_buffer_minutes", models.IntegerField(default=30)),
                ("delivery_buffer_minutes", models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(default="Washer", max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("daily_wage", models.FloatField(default=500.0)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
            ],
            options={
                "verbose_name_plural": "Staff",
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("PICKUP", "Pickup"), ("DELIVERY", "Delivery")],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("capacity", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["kind", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="GarmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("icon", models.CharField(default="Shirt", max_length=50)),
                ("price", models.FloatField(default=0.0)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("PC", "per pc"),
                            ("KG", "per kg"),
                            ("SQFT", "per sq.ft"),
                            ("SET", "per set"),
                        ],
                        default="PC",
                        max_length=8,
                    ),
                ),
                ("turnaround_days", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.garmentcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__display_order", "display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_phone", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLACED", "Placed"),
                            ("PROCESSING", "Processing"),
                            ("IRONING", "Ironing"),
                            ("READY", "Ready"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLACED",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partial"),
                            ("UNPAID", "Unpaid"),
                        ],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                ("payment_method", models.CharField(default="CASH", max_length=50)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("STORE_PICKUP", "Store Pickup"),
                            ("HOME_PICKUP", "Home Pickup"),
                            ("HOME_DELIVERY", "Home Delivery"),
                            ("ONLINE", "Online"),
                        ],
                        default="STORE_PICKUP",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEB", "Web Dashboard"),
                            ("MOBILE_APP", "Mobile App"),
                            ("PUBLIC_PAGE", "Public Page"),
                            ("STAFF_APP", "Staff App"),
                            ("AGENT_APP", "Agent App"),
                        ],
                        default="WEB",
                        max_length=20,
                    ),
                ),
                ("subtotal", models.FloatField(default=0.0)),
                ("delivery_charge", models.FloatField(default=0.0)),
                ("discount_amount", models.FloatField(default=0.0)),
                ("total_amount", models.FloatField(default=0.0)),
                ("paid_amount", models.FloatField(default=0.0)),
                ("due_amount", models.FloatField(default=0.0)),
                ("express", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("placed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_at", models.DateTimeField(blank=True, null=True)),
                ("ironing_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("out_for_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="api.customer",
                    ),
                ),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_orders",
                        to="api.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_title", models.CharField(max_length=255)),
                ("service_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLACED", "Placed"),
                            ("PROCESSING", "Processing"),
                            ("IRONING", "Ironing"),
                            ("READY", "Ready"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLACED",
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("PC", "per pc"),
                            ("KG", "per kg"),
                            ("SQFT", "per sq.ft"),
                            ("SET", "per set"),
                        ],
                        default="PC",
                        max_length=8,
                    ),
                ),
                ("unit_price", models.FloatField(default=0.0)),
                ("total_price", models.FloatField(default=0.0)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.garmentitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("HALF_DAY", "Half Day"),
                            ("LEAVE", "Leave"),
                        ],
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="api.staff",
                    ),
                ),
            ],
            options={
                "unique_together": {("staff", "date")},
            },
        ),
    ]
