# Generated by Django 5.0.6 on 2026-07-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="has_app_login",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_delivery_agent",
            field=models.BooleanField(default=False),
        ),
    ]
