# Generated by Django 5.0.6 on 2026-07-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_staff_has_app_login_staff_is_delivery_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="plan",
            field=models.CharField(default="Pro+", max_length=40),
        ),
        migrations.AddField(
            model_name="shop",
            name="team_login_limit",
            field=models.IntegerField(default=4),
        ),
    ]
