# Generated by Django 5.0.6 on 2026-07-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_shop_plan_shop_team_login_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
