# Generated by Django 5.0.6 on 2026-08-10 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_order_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
