# Generated by Django 5.0.6 on 2026-08-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_expense_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=180),
        ),
    ]
