# Generated by Django 5.0.6 on 2026-08-11 07:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_order_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("amount", models.FloatField()),
                ("paid_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("method", models.CharField(default="CASH", max_length=50)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payments",
                        to="api.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-month", "-paid_on"],
            },
        ),
    ]
