# Generated by Django 5.0.6 on 2026-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_garmentitem_image_url_shop_currency_symbol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="garmentcategory",
            name="turnaround_days",
            field=models.IntegerField(default=1),
        ),
    ]
