# Generated by Django 5.0.6 on 2026-08-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_orderauditlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="default_daily_wage",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="daily_wage",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="is_delivery_agent",
        ),
        migrations.AddField(
            model_name="shop",
            name="default_monthly_wage",
            field=models.FloatField(default=18000.0),
        ),
        migrations.AddField(
            model_name="staff",
            name="monthly_wage",
            field=models.FloatField(default=15000.0),
        ),
    ]
