# Generated by Django 5.2.17 on 2026-09-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_staff_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garmentcategory',
            name='turnaround_days',
        ),
        migrations.RemoveField(
            model_name='garmentitem',
            name='turnaround_days',
        ),
    ]
