# Generated by Django 5.2.17 on 2026-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_garmentcategory_turnaround_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
