# Generated by Django 5.0.6 on 2026-09-17 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_order_scheduled_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarypayment",
            name="expense",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salary_payment",
                to="api.expense",
            ),
        ),
        migrations.CreateModel(
            name="SalaryAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("amount", models.FloatField()),
                ("paid_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI", "UPI"),
                            ("CARD", "Card"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                        ],
                        default="CASH",
                        max_length=50,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_advances",
                        to="api.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-month", "-paid_on"],
            },
        ),
    ]
