# Generated by Django 5.0.6 on 2026-09-23 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_salarypayment_expense_salaryadvance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Service Income", "Service Income"),
                            ("Customer Deposit", "Customer Deposit"),
                            ("Scrap Sale", "Scrap Sale"),
                            ("Investment", "Investment"),
                            ("Refund", "Refund"),
                            ("Other", "Other"),
                        ],
                        default="Service Income",
                        max_length=100,
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI", "UPI"),
                            ("CARD", "Card"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                        ],
                        default="CASH",
                        max_length=50,
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
