# Generated by Django 5.0.6 on 2026-09-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_creditcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="check_in_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="notes",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
