# Generated by Django 4.2.27 on 2026-10-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_role_auth"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="landmark",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="preference",
            field=models.TextField(blank=True, default=""),
        ),
    ]
