# Generated by Django 4.2.27 on 2026-10-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_customer_profile_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(default="WashNLaundry Express", max_length=255),
        ),
    ]
