# Generated by Django 4.2.27 on 2026-10-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_auto_create_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_access_token",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("app_id", models.CharField(blank=True, default="", max_length=120)),
                (
                    "app_secret",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "facebook_page_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "facebook_page_name",
                    models.CharField(
                        blank=True, default="WashNLaundry Official", max_length=255
                    ),
                ),
                (
                    "instagram_account_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "instagram_username",
                    models.CharField(
                        blank=True, default="washnlaundry", max_length=120
                    ),
                ),
                ("auto_reply_enabled", models.BooleanField(default=True)),
                ("is_connected", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_settings",
                        to="api.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetaPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("FACEBOOK", "Facebook"),
                            ("INSTAGRAM", "Instagram"),
                            ("BOTH", "Facebook & Instagram"),
                        ],
                        default="BOTH",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("image_url", models.URLField(blank=True, default="", max_length=1000)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("PUBLISHED", "Published"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "meta_post_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("likes_count", models.IntegerField(default=0)),
                ("comments_count", models.IntegerField(default=0)),
                ("shares_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_posts",
                        to="api.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetaMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("FACEBOOK", "Facebook"),
                            ("INSTAGRAM", "Instagram"),
                            ("BOTH", "Facebook & Instagram"),
                        ],
                        default="INSTAGRAM",
                        max_length=20,
                    ),
                ),
                ("conversation_id", models.CharField(db_index=True, max_length=120)),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("USER", "Customer"),
                            ("AI", "Meta AI"),
                            ("STAFF", "Staff Agent"),
                        ],
                        default="USER",
                        max_length=10,
                    ),
                ),
                ("sender_name", models.CharField(default="Customer", max_length=120)),
                ("sender_id", models.CharField(blank=True, default="", max_length=120)),
                ("text", models.TextField()),
                ("is_lead", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_messages",
                        to="api.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetaLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("FACEBOOK", "Facebook"),
                            ("INSTAGRAM", "Instagram"),
                            ("BOTH", "Facebook & Instagram"),
                        ],
                        default="INSTAGRAM",
                        max_length=20,
                    ),
                ),
                (
                    "ad_campaign",
                    models.CharField(
                        blank=True, default="Organic DM / Promo", max_length=255
                    ),
                ),
                ("customer_name", models.CharField(max_length=120)),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "customer_email",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("inquiry_notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New Lead"),
                            ("CONTACTED", "Contacted"),
                            ("CONVERTED", "Converted to Order"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "converted_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.order",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_leads",
                        to="api.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
