# Generated by Django 4.2.27 on 2026-10-09 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_tenant_data(apps, schema_editor):
    Shop = apps.get_model('api', 'Shop')
    ShopOrderSequence = apps.get_model('api', 'ShopOrderSequence')
    from django.utils.text import slugify

    # 1. Ensure a default Shop exists
    shop = Shop.objects.first()
    if not shop:
        shop = Shop.objects.create(
            name='WashNLaundry Express',
            slug='washnlaundry-express',
            subdomain='express',
            order_prefix='WA3P',
            status='ACTIVE'
        )
    else:
        changed = False
        if not getattr(shop, 'slug', None):
            shop.slug = slugify(shop.name) or 'washnlaundry-express'
            changed = True
        if not getattr(shop, 'subdomain', None):
            shop.subdomain = shop.slug
            changed = True
        if not getattr(shop, 'status', None):
            shop.status = 'ACTIVE'
            changed = True
        if changed:
            shop.save()

    # 2. Backfill Shop foreign keys across all tenant models where shop is null
    tenant_models = [
        'Customer', 'GarmentCategory', 'GarmentItem', 'Order', 'OrderItem',
        'OrderAuditLog', 'ServiceArea', 'TimeSlot', 'Expense', 'CreditCategory',
        'Credit', 'Staff', 'Attendance', 'SalaryPayment', 'SalaryAdvance',
        'Lead', 'EmailLinkRequest'
    ]

    for model_name in tenant_models:
        model = apps.get_model('api', model_name)
        model.objects.filter(shop__isnull=True).update(shop=shop)

    # 3. Initialize ShopOrderSequence for each existing shop
    Order = apps.get_model('api', 'Order')
    for s in Shop.objects.all():
        seq, created = ShopOrderSequence.objects.get_or_create(shop=s)
        if created:
            prefix = s.order_prefix or 'SHOP'
            last_order = (
                Order.objects.filter(shop=s, order_number__startswith=f'{prefix}-')
                .order_by('-order_number').first()
            )
            if last_order and last_order.order_number:
                try:
                    seq.last_number = int(last_order.order_number.rsplit('-', 1)[1])
                except (IndexError, ValueError):
                    seq.last_number = Order.objects.filter(shop=s).count()
            else:
                seq.last_number = Order.objects.filter(shop=s).count()
            seq.save()

    # 4. If PostgreSQL, enable Row-Level Security policies as defense-in-depth
    if schema_editor.connection.vendor == 'postgresql':
        rls_tables = [
            'api_order', 'api_customer', 'api_expense', 'api_credit',
            'api_staff', 'api_attendance', 'api_salarypayment',
            'api_garmentcategory', 'api_garmentitem'
        ]
        for tbl in rls_tables:
            schema_editor.execute(f"ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY;")
            schema_editor.execute(f"""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_policies WHERE tablename = '{tbl}' AND policyname = 'tenant_isolation_policy'
                    ) THEN
                        CREATE POLICY tenant_isolation_policy ON {tbl}
                            USING (shop_id = NULLIF(current_setting('app.current_tenant', true), '')::integer OR current_setting('app.current_tenant', true) IS NULL)
                            WITH CHECK (shop_id = NULLIF(current_setting('app.current_tenant', true), '')::integer OR current_setting('app.current_tenant', true) IS NULL);
                    END IF;
                END $$;
            """)


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0027_create_customers_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credits",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="creditcategory",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_categories",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="emaillinkrequest",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link_requests",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="garmentcategory",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="garmentitem",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="orderauditlog",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="salaryadvance",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_advances",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="salarypayment",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_payments",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_areas",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="custom_domain",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="shop",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="status",
            field=models.CharField(default="ACTIVE", max_length=20),
        ),
        migrations.AddField(
            model_name="shop",
            name="subdomain",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="staff",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_members",
                to="api.shop",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_slots",
                to="api.shop",
            ),
        ),
        migrations.AlterField(
            model_name="creditcategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="creditcategory",
            unique_together={("shop", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("shop", "phone")},
        ),
        migrations.AlterUniqueTogether(
            name="garmentcategory",
            unique_together={("shop", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("shop", "order_number")},
        ),
        migrations.CreateModel(
            name="ShopOrderSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_sequence",
                        to="api.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("STAFF", "Staff"),
                            ("CUSTOMER", "Customer"),
                        ],
                        default="STAFF",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="api.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "created_at"],
                "unique_together": {("user", "shop")},
            },
        ),
        migrations.RunPython(backfill_tenant_data, reverse_backfill),
    ]

