# Generated by Django 5.2.18 on 2026-10-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_metasettings_metapost_metamessage_metalead'),
        ('api', '0028_tenant_schema_and_backfill'),
    ]

    operations = [
    ]
