# Generated by Django 4.2.27 on 2026-10-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_merge_20261009_1825"),
    ]

    operations = [
        migrations.AddField(
            model_name="metapost",
            name="media_type",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="metapost",
            name="permalink",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="business_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="facebook_followers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="instagram_followers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="instagram_media_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="profile_picture_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="user_access_token",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="metapost",
            name="image_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
