# Generated by Django 4.2.27 on 2026-10-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_metapost_media_type_metapost_permalink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metasettings",
            name="whatsapp_business_account_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="whatsapp_phone_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="whatsapp_phone_number_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="metalead",
            name="platform",
            field=models.CharField(
                choices=[
                    ("FACEBOOK", "Facebook"),
                    ("INSTAGRAM", "Instagram"),
                    ("WHATSAPP", "WhatsApp"),
                    ("BOTH", "Facebook & Instagram"),
                ],
                default="INSTAGRAM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="metamessage",
            name="platform",
            field=models.CharField(
                choices=[
                    ("FACEBOOK", "Facebook"),
                    ("INSTAGRAM", "Instagram"),
                    ("WHATSAPP", "WhatsApp"),
                    ("BOTH", "Facebook & Instagram"),
                ],
                default="INSTAGRAM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="metapost",
            name="platform",
            field=models.CharField(
                choices=[
                    ("FACEBOOK", "Facebook"),
                    ("INSTAGRAM", "Instagram"),
                    ("WHATSAPP", "WhatsApp"),
                    ("BOTH", "Facebook & Instagram"),
                ],
                default="BOTH",
                max_length=20,
            ),
        ),
    ]
