# Generated by Django 4.2.27 on 2026-10-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_prepare_shop_lifecycle_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                    ("ARCHIVED", "Archived"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="shop",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subdomain", ""), _negated=True),
                fields=("subdomain",),
                name="shop_subdomain_unique_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="shop",
            constraint=models.UniqueConstraint(
                condition=models.Q(("custom_domain", ""), _negated=True),
                fields=("custom_domain",),
                name="shop_custom_domain_unique_when_set",
            ),
        ),
    ]
