# Generated by Django 4.2.27 on 2026-10-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_dedupe_order_prefixes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shop",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order_prefix", ""), _negated=True),
                fields=("order_prefix",),
                name="shop_order_prefix_unique_when_set",
            ),
        ),
    ]
