# Generated by Django 4.2.27 on 2026-10-10 20:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_shop_order_prefix_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("VIDEO", "Video")], max_length=10
                    ),
                ),
                ("content_type", models.CharField(max_length=100)),
                (
                    "original_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("size", models.BigIntegerField(default=0)),
                ("storage_key", models.CharField(max_length=300, unique=True)),
                ("status", models.CharField(default="PENDING", max_length=10)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="api.order",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_media",
                        to="api.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
