# Generated by Django 4.2.27 on 2026-10-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_order_media"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderMediaBlob",
            fields=[
                (
                    "media",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="blob",
                        serialize=False,
                        to="api.ordermedia",
                    ),
                ),
                ("data", models.BinaryField()),
            ],
        ),
    ]
